---
title: "FragPipeAnalystR Get Started Tutorial"
output:
  html_document:
    keep_md: yes
---

# Introduction

FragPipeAnalystR is a R package intended for FragPipe downstream analysis. We also make it compatible with the result obtained from FragPipe-Analyst. Users are able to reproduce and customize the plots generated in FragPipe-Analyst.

## Quick Start Example
``` {r include=T, warning=F, cache=F}
library(FragPipeAnalystR)
data("ccrcc", package = "FragPipeAnalystR")
```

``` {r include=T, warning=F}
print(metadata(ccrcc))
```

``` {r include=T, warning=F}
print(head(rownames(ccrcc)))
```

``` {r include=T, warning=F}
print(colnames(rowData(ccrcc)))
```

``` {r include=T, warning=F}
print(head(rowData(ccrcc)$ID))
```

``` {r include=T, warning=F}
plot_pca(ccrcc)
```

``` {r include=T, warning=F}
plot_correlation_heatmap(ccrcc)
```

``` {r include=T, warning=F}
plot_missval_heatmap(ccrcc)
```

``` {r include=T, warning=F}
plot_feature_numbers(ccrcc)
```

```{r include=T, warning=F}
plot_feature(ccrcc, c("CA9", "AHNAK2", "NDUFV2", "PIGR"))
```

```{r include=T, warning=F}
de_result <- test_limma(ccrcc, type = "all")
de_result_updated <- add_rejections(de_result)
```

```{r include=T, warning=F}
plot_volcano(de_result_updated, "Tumor_vs_NAT")
```

``` {r include=T, warning=F}
or_result <- or_test(de_result_updated, database = "Hallmark", direction = "UP")
plot_or(or_result)
```

```{r include=T, warning=F}
or_result <- or_test(de_result_updated, database = "Hallmark", direction = "DOWN")
plot_or(or_result)
```

``` {r include=T, warning=F}
sessionInfo()
```
